/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Google84daecdce0f066deDothtmlRouteImport } from './routes/google84daecdce0f066de[.]html'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BinListIndexRouteImport } from './routes/bin-list.index'
import { Route as TicketIdRouteImport } from './routes/ticket.$id'
import { Route as BinListCountryRouteImport } from './routes/bin-list.$country'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Google84daecdce0f066deDothtmlRoute =
  Google84daecdce0f066deDothtmlRouteImport.update({
    id: '/google84daecdce0f066de.html',
    path: '/google84daecdce0f066de.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BinListIndexRoute = BinListIndexRouteImport.update({
  id: '/bin-list/',
  path: '/bin-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIdRoute = TicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BinListCountryRoute = BinListCountryRouteImport.update({
  id: '/bin-list/$country',
  path: '/bin-list/$country',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/google84daecdce0f066de.html': typeof Google84daecdce0f066deDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bin-list/$country': typeof BinListCountryRoute
  '/ticket/$id': typeof TicketIdRoute
  '/bin-list/': typeof BinListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/google84daecdce0f066de.html': typeof Google84daecdce0f066deDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bin-list/$country': typeof BinListCountryRoute
  '/ticket/$id': typeof TicketIdRoute
  '/bin-list': typeof BinListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/google84daecdce0f066de.html': typeof Google84daecdce0f066deDothtmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bin-list/$country': typeof BinListCountryRoute
  '/ticket/$id': typeof TicketIdRoute
  '/bin-list/': typeof BinListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/google84daecdce0f066de.html'
    | '/sitemap.xml'
    | '/bin-list/$country'
    | '/ticket/$id'
    | '/bin-list/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/google84daecdce0f066de.html'
    | '/sitemap.xml'
    | '/bin-list/$country'
    | '/ticket/$id'
    | '/bin-list'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/google84daecdce0f066de.html'
    | '/sitemap.xml'
    | '/bin-list/$country'
    | '/ticket/$id'
    | '/bin-list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  Google84daecdce0f066deDothtmlRoute: typeof Google84daecdce0f066deDothtmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BinListCountryRoute: typeof BinListCountryRoute
  TicketIdRoute: typeof TicketIdRoute
  BinListIndexRoute: typeof BinListIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google84daecdce0f066de.html': {
      id: '/google84daecdce0f066de.html'
      path: '/google84daecdce0f066de.html'
      fullPath: '/google84daecdce0f066de.html'
      preLoaderRoute: typeof Google84daecdce0f066deDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bin-list/': {
      id: '/bin-list/'
      path: '/bin-list'
      fullPath: '/bin-list/'
      preLoaderRoute: typeof BinListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$id': {
      id: '/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof TicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bin-list/$country': {
      id: '/bin-list/$country'
      path: '/bin-list/$country'
      fullPath: '/bin-list/$country'
      preLoaderRoute: typeof BinListCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  Google84daecdce0f066deDothtmlRoute: Google84daecdce0f066deDothtmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BinListCountryRoute: BinListCountryRoute,
  TicketIdRoute: TicketIdRoute,
  BinListIndexRoute: BinListIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
