/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketIdRouteImport } from './routes/ticket.$id'
import { Route as ForumThreadIdRouteImport } from './routes/forum_.$threadId'

const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketIdRoute = TicketIdRouteImport.update({
  id: '/ticket/$id',
  path: '/ticket/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumThreadIdRoute = ForumThreadIdRouteImport.update({
  id: '/forum_/$threadId',
  path: '/forum/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forum': typeof ForumRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forum': typeof ForumRoute
  '/forum/$threadId': typeof ForumThreadIdRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forum': typeof ForumRoute
  '/forum_/$threadId': typeof ForumThreadIdRoute
  '/ticket/$id': typeof TicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/forum'
    | '/forum/$threadId'
    | '/ticket/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/forum'
    | '/forum/$threadId'
    | '/ticket/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/forum'
    | '/forum_/$threadId'
    | '/ticket/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ForumRoute: typeof ForumRoute
  ForumThreadIdRoute: typeof ForumThreadIdRoute
  TicketIdRoute: typeof TicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$id': {
      id: '/ticket/$id'
      path: '/ticket/$id'
      fullPath: '/ticket/$id'
      preLoaderRoute: typeof TicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum_/$threadId': {
      id: '/forum_/$threadId'
      path: '/forum/$threadId'
      fullPath: '/forum/$threadId'
      preLoaderRoute: typeof ForumThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ForumRoute: ForumRoute,
  ForumThreadIdRoute: ForumThreadIdRoute,
  TicketIdRoute: TicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
